version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: ${APP_NAME}_SK
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    nginx:
        image: nginx:stable
        container_name: ${APP_NAME}_SK_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www:rw
            - ./docker/nginx:/etc/nginx/conf.d:rw

    postgres:
        image: postgres:latest
        container_name: ${APP_NAME}_SK_postgres
        ports:
            - "5433:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
